services:
  comfy-smartgallery:
    image: mmartial/smart-comfyui-gallery:latest
    container_name: comfy-smartgallery
    ports:
      - 8189:8189
    volumes:
      - /comfyui-nvidia/basedir/output:/mnt/output
      - /comfyui-nvidia/basedir/input:/mnt/input
      - /comfyui-nvidia/SmartGallery:/mnt/SmartGallery
#      - /tmp:/deleteto
#      - /etc/localtime:/etc/localtime:ro
      # To use the "Link External Folders" feature, add external locations to be mounted within the container
#      - /path/to/your/ExternalFolder:/mnt/ExternalFolder
    restart: unless-stopped
    environment:
      - BASE_OUTPUT_PATH=/mnt/output
      - BASE_INPUT_PATH=/mnt/input
      - BASE_SMARTGALLERY_PATH=/mnt/SmartGallery
      # Adapt to wanted values (use id -u and id -g to obtain values)
      - WANTED_UID=1000
      - WANTED_GID=1000
      # Set to true to force chown of the BASE_SMARTGALLERY_PATH folder only
#      - FORCE_CHOWN=true
#      - DELETE_TO=/deleteto
      # Seeds the first Remix backend. Add/reorder more backends in the Remix UI.
      - COMFYUI_SERVER_URL=http://192.168.100.1:8188
